/**
 * Internal dependencies.
 */
import * as helpers from '../../../../.dev/tests/jest/helpers';
import { name, settings } from '../index';
import googleFonts from '../../../components/font-family/fonts';

const variations = {
	className: [ undefined, '', 'random classes' ],
	anchor: [ undefined, '' ], // TODO: figure out how to test this core attribute.
	align: [ '', 'wide', 'full', 'left', 'center', 'right' ],
	verticalAlignment: [ undefined, 'top', 'center', 'bottom' ],
	gutter: [ 'none', 'small', 'medium', 'large', 'xlarge' ],
	layout: [ undefined, '', '100', '50-50', '25-75', '75-25', '66-33', '33-66', '33-33-33', '50-25-25', '25-25-50', '25-50-25', '20-60-20', '25-25-25-25', '40-20-20-20', '20-20-20-40' ],
	columns: [ 1, 2, 3, 4 ],
	id: [ undefined, 0, 12345 ],
	coblocks: [ undefined, {}, { id: undefined }, { id: 'testing' } ],
	textColor: [ undefined, 'primary' ],
	customTextColor: [ undefined, '#123456' ],
	lineHeight: [ undefined, 0, 3, 2.5 ],
	letterSpacing: [ undefined, 0, 3, -1, 2.5 ],
	fontWeight: [ undefined, '', 'normal', 'bold', '100', '200', '300', '400', '500', '600', '700', '800', '900' ],
	textTransform: [ undefined, '', 'uppercase', 'lowercase', 'capitalize', 'initial' ],
	isStackedOnMobile: [ true, false ],
	noBottomSpacing: [ undefined, true, false ],
	noTopSpacing: [ undefined, true, false ],
	noBottomMargin: [ undefined, true, false ],
	noTopMargin: [ undefined, true, false ],
	paddingTop: [ 0, 100 ],
	paddingRight: [ 0, 100 ],
	paddingBottom: [ 0, 100 ],
	paddingLeft: [ 0, 100 ],
	paddingTopTablet: [ 0, 100 ],
	paddingRightTablet: [ 0, 100 ],
	paddingBottomTablet: [ 0, 100 ],
	paddingLeftTablet: [ 0, 100 ],
	paddingTopMobile: [ 0, 100 ],
	paddingRightMobile: [ 0, 100 ],
	paddingBottomMobile: [ 0, 100 ],
	paddingLeftMobile: [ 0, 100 ],
	paddingUnit: [ 'px', 'em', '%' ],
	paddingSize: [ 'no', 'small', 'medium', 'large', 'advanced' ],
	paddingSyncUnits: [ true, false ],
	paddingSyncUnitsTablet: [ true, false ],
	paddingSyncUnitsMobile: [ true, false ],
	marginTop: [ 0, 100 ],
	marginRight: [ 0, 100 ],
	marginBottom: [ 0, 100 ],
	marginLeft: [ 0, 100 ],
	marginTopTablet: [ 0, 100 ],
	marginRightTablet: [ 0, 100 ],
	marginBottomTablet: [ 0, 100 ],
	marginLeftTablet: [ 0, 100 ],
	marginTopMobile: [ 0, 100 ],
	marginRightMobile: [ 0, 100 ],
	marginBottomMobile: [ 0, 100 ],
	marginLeftMobile: [ 0, 100 ],
	marginUnit: [ 'px', 'em', '%' ],
	marginSize: [ 'no', 'small', 'medium', 'large', 'advanced' ],
	marginSyncUnits: [ true, false ],
	marginSyncUnitsTablet: [ true, false ],
	marginSyncUnitsMobile: [ true, false ],
	hasMarginControl: [ true, false ],
	linkTo: [ undefined, 'none', 'media', 'attachment', 'custom' ],
	target: [ '', '_blank', '_self', '_parent' ],
	rel: [ '', 'alternate', 'author', 'preload' ],
	gutter: [ 0, 10, 100 ],
	gutterMobile: [ 0, 10, 100 ],
	radius: [ undefined, 0, 20 ],
	shadow: [ undefined, 'none', 'sml', 'med', 'lrg', 'xlrg' ],
	filter: [ 'none', 'grayscale', 'sepia', 'saturation', 'dim', 'vintage' ],
	captions: [ undefined, true, false ],
	captionStyle: [ 'none', 'dark', 'light' ],
	captionColor: [ undefined, 'primary' ],
	customCaptionColor: [ undefined, '#123456' ],
	primaryCaption: [ undefined, '', 'caption text' ],
	backgroundRadius: [ undefined, 0, 20 ],
	backgroundPadding: [ undefined, 'none', 'small', 'medium', 'large', 'xlarge' ],
	backgroundPaddingMobile: [ undefined, 'none', 'small', 'medium', 'large', 'xlarge' ],
	lightbox: [ undefined, true, false ],
	backgroundType: [ undefined, '', 'image', 'video' ],
	backgroundImg: [ undefined, '', 'https://website.com/wp-content/uploads/1234/56/image.jpg', 'https://website.com/wp-content/uploads/1234/56/video.mp4' ],
	backgroundPosition: [ undefined, '' ],
	hasAlignmentControls: [ true, false ],
	hasStackedControl: [ true, false ],
	backgroundRepeat: [ 'no-repeat', 'repeat', 'repeat-x', 'repeat-y' ],
	backgroundSize: [ 'cover', 'contain' ],
	backgroundOverlay: [ 0, 100 ],
	backgroundColor: [ undefined, 'primary' ],
	customBackgroundColor: [ '#123456' ],
	hasParallax: [ undefined, true, false ],
	focalPoint: [ undefined, { x: 0, y: 0 }, { x: 0.33663366336633666, y: 0.8335193452380952 } ],
	videoMuted: [ undefined, true, false ],
	videoLoop: [ undefined, true, false ],
	openPopover: [ undefined, true, false ],
	gridSize: [ 'none', 'sml', 'med', 'lrg', 'xlrg' ],
	height: [ undefined, 0, 400 ],
	pageDots: [ undefined, true, false ],
	prevNextButtons: [ undefined, true, false ],
	autoPlay: [ undefined, true, false ],
	autoPlaySpeed: [ undefined, 0, 1000, 3000 ],
	draggable: [ undefined, true, false ],
	alignCells: [ undefined, true, false ],
	pauseHover: [ undefined, true, false ],
	freeScroll: [ undefined, true, false ],
	thumbnails: [ undefined, true, false ],
	responsiveHeight: [ undefined, true, false ],
};

helpers.testDeprecatedBlockVariations( name, settings, variations );
