name: 'Translation'

on:
  pull_request:
    branches:
      - master

jobs:
  update:
    name: Localization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GoDaddy Git User
        uses: godaddy-wordpress/setup-godaddy-git-user@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@main

      # Yarn is still required on this project, so we need to make sure it is
      # installed globally.
      - name: Install yarn
        run: |
          npm i -g yarn

      - name: Install dependencies
        run: |
          composer install --prefer-dist --optimize-autoloader
          yarn install --immutable

      - name: Create translations
        run: |
          yarn makepot

      - name: Commit changes
        shell: bash
        run: |
          if [ ! -z "$(git status languages/go.json --porcelain)" ]; then
            git add languages/go.json
            git add languages/go.pot
            git commit -m "[BOT] Update language translations" --no-verify
            git reset --hard
            git push --quiet
          else
            echo "No language translations to update."
          fi
