name: Test / Accessibility

on:
  pull_request:
    branches:
      - master

jobs:
  pa11y:
    name: Pa11y
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup wp-env
        uses: godaddy-wordpress/setup-wp-env@v1
        with:
          core: 'WordPress/WordPress#6.1'
          phpVersion: '7.4'
          plugins: '[".","https://downloads.wordpress.org/plugin/woocommerce.zip"]'
          themes: '["https://downloads.wordpress.org/theme/go.zip"]'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1

      - name: Install dependencies
        run: |
          npm i -g yarn
          composer install
          yarn install --immutable

      - name: Build plugin
        run: |
          npx grunt build
          mv ./build/coblocks $(wp-env install-path)/tests-WordPress/wp-content/plugins/

      - name: Prepare tests
        run: |
          wp-env run tests-cli "wp db import wp-content/plugins/coblocks/.dev/tests/a11y/coblocks_pa11y.sql"

      - name: Run tests
        run: |
          A11Y=$(yarn test:a11y)
          echo "$A11Y"
          if [[ $A11Y != *"All accessibility tests have passed"* ]]; then
            exit 1
          fi
