name: 'Validation / Coding Standards'

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - uses: actions/checkout@v2

      - name: Composer Install
        run: composer install --prefer-dist --optimize-autoloader

      - name: PHPCS
        run: composer lint

  css:
    runs-on: ubuntu-latest
    name: CSS
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Yarn Install
        run: yarn install

      - name: Run stylelint
        run: yarn lint:css

  js:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Yarn Install
        run: yarn install

      - name: Run eslint
        run: yarn lint:js
