name: 'Validation / Coding Standards'

on: push

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - uses: actions/checkout@v2

      - name: Composer Install
        run: composer install --prefer-dist --optimize-autoloader

      - name: PHPCS
        run: composer lint

  css:
    runs-on: ubuntu-latest
    name: CSS
    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn install

      - name: Run stylelint
        run: yarn lint:css

  js:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn install

      - name: Run eslint
        run: yarn lint:js
